
[U20]
lcd_read_id = 0xD3

# Section info
string_config_h_author = Hobi, tpruvot, gdepuille (ini file port)
custom_status_screen_image = on

# Section machine
motherboard = BOARD_LONGER3D_LK

# Section serial
serial_port = 1
baud_rate_gcode = on
custom_machine_name = Alfawise U20

# Section psu control
psu_name = 360W 24V/15A

# Section hotend temp
default_kp = 17.22
default_ki = 1.00
default_kd = 74.22

# Section bed temp
pidtempbed = on
default_bed_kp = 841.68
default_bed_ki = 152.12
default_bed_kd = 1164.25

# Section safety
thermal_protection_chamber = off

# Section endstops
endstoppullups = off
x_min_endstop_inverting = true
y_min_endstop_inverting = true
z_min_endstop_inverting = true
x_max_endstop_inverting = true
y_max_endstop_inverting = true
z_max_endstop_inverting = true
endstop_interrupts_feature = on

# Section motion
default_axis_steps_per_unit = { 80, 80, 400, 98 }
default_max_feedrate = { 200, 200, 100, 25 }
limited_max_fr_editing = on
max_feedrate_edit_vamlues = { 250, 250, 200, 50 }
default_max_acceleration = { 200, 200, 100, 3000 }
limited_max_accel_editing = on
max_accel_edit_values = { 600, 600, 400, 6000 }
default_acceleration = 200
default_retract_acceleration = 500
default_travel_acceleration = 200
classic_jerk = on
default_zjerk = 0.4
limited_jerk_editing = on
junction_deviation_mm = 0.10

# Section probes
probe_manually = on
xy_probe_feedrate = (80*60)
z_probe_feedrate_fast = (7*60)

# Section motion
invert_x_dir = true
invert_y_dir = false
invert_z_dir = true

# Section geometry
x_bed_size = 300
y_bed_size = 300
z_max_pos = 400

# Section filament runout sensors
filament_runout_sensor = on
fil_runout_state = HIGH
fil_runout_pullup = off

# Section calibrate
mesh_bed_leveling = on
lcd_bed_tramming = on
bed_tramming_height = 0.2

# Section homing
homing_feedrate_mm_m = { (40*60), (40*60), (6*60) }

# Section eeprom
eeprom_settings = on

# Section temperature
preheat_1_label = "PLA Chro."
preheat_1_temp_hotend = 210
preheat_1_temp_bed = 60

preheat_2_label = "ABS"
preheat_2temp_hotend = 250
preheat_2_temp_bed = 100

# Section nozzle park
nozzle_park_feature = on
nozzle_park_move = 1
nozzle_park_xy_feedrate = 50
nozzle_park_z_feedrate = 6

# Section interface
lcd_language = en
sdsupport = on
individual_axis_homing_menu = on
longer_lk_tft28 = on
tft_classic_ui = on
touch_screen = on
button_delay_edit = 75
button_delay_menu = 100
touch_calibration_x = 12000
touch_calibration_y = -9000
touch_offset_x = -43
touch_offset_y = 257

# --------------- ADVANCED --------------- #
thermal_protection_period = 60
thermal_protection_hysteresis = 10
watch_temp_period = 60
fan_min_pwm = TERN(MAPLE_STM32F1, 35, 5)
fan_max_pwm = 255
homing_bump_divisor = { 4, 4, 4 }
lcd_info_menu = on
set_progress_manually = on
set_remaining_time = off
menu_addautostart = on
event_gcode_sd_abort = "G28X"
power_loss_recovery = on
sdcard_sort_alpha = on
sdsort_gcode = true
sdsort_uses_ram = true
sdsort_cache_names = true
long_filename_host_support = on
sd_reprint_last_selected_file = on
status_heat_percent = on
lcd_language_2 = fr
lcd_language_auto_save = on
tft_marlinui_color = COLOR_WHITE
tft_marlinbg_color = COLOR_BLACK
tft_disabled_color = 0x10A2
tft_btcancel_color = COLOR_RED
tft_btarrows_color = COLOR_WHITE
tft_btokmenu_color = COLOR_BLUE
block_buffer_size = 32
buffsize = 8
emergency_parser = on
advanced_pause_feature = on
advanced_pause_purge_length = 25
filament_load_unload_gcodes = on
soft_reset_via_serial = on